### PR TITLE
Reintroduce multiple layers selection in Leaflet demo

### PR DESCRIPTION
**Pull request by edigiacomo**
This PR reintroduce the multiple layer selection in the Leaflet demo as requested in PR #36 (I created a new PR because a merged PR cannot be reopened).

The layer selection is a simple `<select multiple>`: it works but it's not very nice, I could use a dropdown menu using a jquery plugin (e.g. https://www.jqueryscript.net/demo/Searchable-Multi-select-jQuery-Dropdown/). What do you think?

image

### CODE REVIEW

**Comment by sylvielamythepaut** [comment]
Hi,

I am trying your new code, but can not make a multiple selection, maybe  I do not know how to do that ..
Also selecting "all layers" will show an error message in the console. 

Is there a way to remove the icon at the top right corner of the leaflet widget, since the layers are not listed there  anymore.

**Comment by sylvielamythepaut** [comment]
Sorry, I was wrong .. I was not on the right branch .. Then I managed to get several layers, my new problem is that I can not pick and choose, it always select all the layers between my 2 clicks ..
Thanks,

Sylvie

**Comment by edigiacomo** [comment]
> Then I managed to get several layers, my new problem is that I can not pick and choose, it always select all the layers between my 2 clicks ..

Have you tried with ctrl + click?

> Also selecting "all layers" will show an error message in the console.

"All layers" contains all the layers, but the `<name>` tag is missing in the GetCapabilities response for this layers: the HTTP GET querystring contains the param `..&layers=&..` (i.e. an empty layer name) and the server fails (HTTP 500) with the following error:

```
skinnywms.errors.LayerNotDefined: Unknown layer ''
```

I could disable the "All Layers" layer: the user can still select all the layers from the menu.

**Comment by sylvielamythepaut** [comment]
Hi,
It is me again..
I am still struggling with the new interface. The layer selection menu at the top keeps disappearing  for me . ( on safari) The multiple selection seems to be ok but, I have no feedback on the menu which layers are being displayed. 
Do you think, you could improve it ?

Thanks a lot,
Sylvie

**Comment by edigiacomo** [comment]
Hi Sylvie, in the last month we are experimenting with the [Leaflet TimeDimension plugin](https://github.com/socib/Leaflet.TimeDimension) (developed by the Balearic Island Coastal Observing and Forecasting System).

Features:

* Multiple layers selection
* Time selection
* Animation
* Legend of the selected layers

Below a very short screencast:

animation

You can try it `ARPA-SIMC:leaflet-time-dimension` branch. We think that this is a better solution: if you agree I can close this PR and open another one to merge the `leaflet-time-dimension` branch.

**Comment by sylvielamythepaut** [comment]
Hi,
Looks very nice,
I will try it now

**Comment by sylvielamythepaut** [comment]
Very nice..
I am more than happy to merge it .. 
In the mean time, we have have introduced the possibility to add tailored basemap ( using your own shapefile) .. If you are interested, I can tell you a bit more.. 

Thanks

Sylvie

**Comment by edigiacomo** [comment]
I opened #44, feel free to close this PR.

> In the mean time, we have have introduced the possibility to add tailored basemap ( using your own shapefile) .. If you are interested, I can tell you a bit more..

Yes, thanks!

**Comment by sylvielamythepaut** [comment]
Thanks, 
I close this one, and merge  #44 instead

**Pull request closed without merging**
