### PR TITLE
Simple time interface in the Leaflet demo

### PR DESCRIPTION
**Pull request by edigiacomo**
I added a simple time interface in the Leaflet demo.

When loaded, the page shows the list of the available layers in the top left. The time drop-down list and the prev/next buttons are disabled.

image

The time list and the time navigation buttons are enabled when a layer with time dimension is selected. The time list is then populated with the available times for the layer (ISO8601 time intervals `YYYY-mm-ddTHH:MM:SSZ/YYYY-mm-ddTHH:MM:SSZ/PTX[HM]` are expanded) and the earliest time is selected and showed on the map. When the user changes the time from the list or clicks the prev/next buttons, the corresponding map is showed.

When the user select another layer, the time list changes accordingly and the earliest time is selected and loaded on the map etc. (or disabled if the layer has no time values).

image

image

There's a limitation: only one layer at a time can be showed on the map over the background, because I wouldn't know how to create the time list when more than one layers is selected (union or intersection of the available times for the selected layers), but we can discuss it and I'll gladly implement a solution (if this PR is of some interest to you).

### CODE REVIEW

**Comment by sylvielamythepaut** [comment]
Great, Thanks .. 
I am going to merge it very soon

**Comment by sylvielamythepaut** [comment]
Hi, 
I have a request for the new demo. I think we have lost the ability of overlaying several layers on the same map .
Is this something you could add ?
Thanks,

**Comment by edigiacomo** [comment]
Yes, I can add this feature. It's ok if the available time values in the selection options will be the union of the available times values for the selected layers?

E.g. let's say that I have:
* Layer1 without time values (e.g. "Grid" or "Boundaries")
* Layer2 with time values T1, T2
* Layer3 with time values T2, T3

If I select Layer1 only, the time list is empty and disabled. If I add Layer2, then the time list is populated with T1, T2 ( = {empty set} + {T1,T2}). If I add Layer3 too, the time list becomes T1, T2, T3 ( = {empty set} + {T1,T2} + {T2,T3}). If I remove Layer2 the time list becomes T2,T3 (= {empty set} + {T2, T3}).

Can I assume that only one time value can be selected (i.e. the same time value for each selected layer)?

**Comment by sylvielamythepaut** [comment]
Just to make sure : 
in your example, if you select the 3 layers ( L1, L2, L3) and the time T1, I assume I will only see L1 and L2 since L3 is not available for T2 ?

**Pull request merged**
