### PR TITLE
Clean up temporary files

### PR DESCRIPTION
**Pull request by brancomat**
Partially addresses #10 

This pull request deletes temporary files after they have been served via flask.
(it seems there are several ways to achieve this so please check the code to see if it's ok for you)

### CODE REVIEW

**Comment by sylvielamythepaut** [comment]
Hi,
Thanks a lot for your contribution , we had a close look at it , and would like to suggest few minors changes..
1- make the global variable file_remover = FileRemover(), a property of the WmsServer Object itself. 
2- in the function _do_cleanup
       2.1: replace the print by the equivalent call to LOG.info 
       2.2: add a try/catch around the remove action

Thanks again
Sylvie

**Comment by brancomat** [comment]
Thanks for the suggestions, I tried to integrate them.
I'm not sure about your policy on logger levels, now the "Deleting ..." message is a debug log, while if the remove action fails it throws a `LOG.exception`

**Comment by sylvielamythepaut** [comment]
Few more comments from our python expert:
Yes, it is perfectly right to use LOG.exception.. But he will recommend to use the following style for all the logging messages.
LOG.info("MY text %s... %s", info1, info2) 
He also recommend to add Exception in the except directive..
Ie 
except Exception:
Thanks again .
Sylvie

**Comment by brancomat** [comment]
I incorporated the recommendation above.

**Pull request merged**
